const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{PrismaClient}=require('@prisma/client');
const db=new PrismaClient(),base='http://127.0.0.1:3000',catalog=require('./data/catalogo.json');let fixture,orderId,customerId;
const input={name:'Cliente Teste',phone:'11900000000',whatsapp:'11900000000',email:'teste@example.com',cep:'01001000',street:'Rua Teste',number:'1',district:'Centro',city:'São Paulo',state:'SP',paymentMethod:'WHATSAPP',checkoutKey:randomUUID(),total:1,shipping:0,discount:999999};
async function call(path,body,method='POST',cookie=''){const r=await fetch(base+path,{method,headers:{'Content-Type':'application/json',cookie},body:JSON.stringify(body)});return [r,await r.json()]}
(async()=>{for(let i=0;i<70;i++){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,500))}
const products=await db.product.findMany({where:{status:'ACTIVE'}}),categories=await db.category.findMany({where:{products:{some:{status:'ACTIVE'}}}});assert.equal(products.length,86);assert.equal(categories.length,9);
for(const item of catalog){const p=products.find(p=>p.sku===item.sku);assert.equal(p.price,item.price);assert.ok(require('fs').existsSync('public'+item.image))}
for(const c of categories){const r=await fetch(base+'/categorias/'+c.slug);assert.equal(r.status,200);const html=await r.text();for(const p of products)assert.equal(html.includes('data-sku="'+p.sku+'"'),p.categoryId===c.id)}
assert.equal((await fetch(base+'/categorias/inexistente')).status,404);assert.equal((await fetch(base+'/admin',{redirect:'manual'})).status,307);assert.equal((await call('/api/admin/products',{id:1,price:100,stock:10},'PATCH'))[0].status,401);assert.equal((await call('/api/payments/webhook',{type:'payment',data:{id:'1'}}))[0].status,401);
const password=require('fs').readFileSync('.env','utf8').match(/ADMIN_PASSWORD="(.*?)"/)[1], [auth]=await call('/api/admin/login',{password});assert.equal(auth.status,200);const cookie=auth.headers.get('set-cookie').split(';')[0];
fixture=await db.product.create({data:{name:'Produto temporário',slug:'test-'+randomUUID(),sku:'TEST-'+randomUUID(),price:1200,stock:0,stockConfirmed:false,priceConfirmed:false,description:'Teste',categoryId:categories[0].id,inventory:{create:{quantity:0}}}});
const body={...input,items:[{productId:fixture.id,quantity:2}]};
for(const invalid of [{...body,items:[]},{...body,items:[{productId:999999,quantity:1}]},{...body,items:[{productId:fixture.id,quantity:1},{productId:fixture.id,quantity:1}]}])assert.equal((await call('/api/orders',invalid))[0].status,400);
const [r,data]=await call('/api/orders',body);assert.equal(r.status,200);assert.equal(data.quote,true);assert.ok(data.whatsappUrl.startsWith('https://wa.me/5511940216955?'));assert.ok(data.message.includes(data.number));const order=await db.order.findUnique({where:{number:data.number}});orderId=order.id;customerId=order.customerId;assert.equal(order.total,2400);assert.equal(order.status,'AGUARDANDO_CONFIRMACAO');assert.equal((await db.product.findUnique({where:{id:fixture.id}})).stock,0);assert.equal((await call('/api/orders',body))[1].number,data.number);assert.equal(await db.order.count({where:{checkoutKey:input.checkoutKey}}),1);assert.equal((await fetch(base+data.orderUrl)).status,200);
assert.equal((await call('/api/payments',{token:order.accessToken}))[0].status,409);
assert.equal((await call('/api/admin/products',{id:fixture.id,price:1500,stock:10},'PATCH',cookie))[0].status,200);
assert.equal((await call('/api/admin/orders',{id:order.id},'POST',cookie))[0].status,200);const confirmed=await db.order.findUnique({where:{id:order.id}});assert.equal(confirmed.quote,false);assert.equal(confirmed.total,4500);assert.equal((await db.product.findUnique({where:{id:fixture.id}})).stock,8);assert.equal((await db.inventory.findUnique({where:{productId:fixture.id}})).quantity,8);assert.equal((await call('/api/admin/orders',{id:order.id},'POST',cookie))[0].status,400);
assert.equal((await call('/api/payments',{token:order.accessToken}))[0].status,409);assert.equal(await db.payment.count({where:{orderId:order.id}}),0);
assert.equal((await call('/api/orders',{...body,checkoutKey:randomUUID(),paymentMethod:'ONLINE'}))[0].status,503);
console.log('PASS API: 86 produtos/fotos/preços, 9 categorias filtradas, admin protegido, pedido a confirmar, idempotência, WhatsApp real do catálogo, confirmação administrativa, reserva de estoque, gateway não configurado e webhook inválido.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(orderId)await db.order.delete({where:{id:orderId}});if(customerId)await db.customer.delete({where:{id:customerId}});if(fixture)await db.product.delete({where:{id:fixture.id}});await db.$disconnect()});
