const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{chromium}=require('playwright'),{PrismaClient}=require('@prisma/client');const db=new PrismaClient();let browser,order,customerId;
(async()=>{let executablePath=process.env.GF_BROWSER,args=["--no-sandbox","--disable-dev-shm-usage","--single-process","--no-zygote","--disable-gpu","--disable-software-rasterizer"];if(!executablePath){const binary=(await import('@sparticuz/chromium')).default;executablePath=await binary.executablePath();args=[...binary.args.filter(a=>!a.startsWith("--use-gl")&&!a.startsWith("--use-angle")&&a!=="--in-process-gpu"),"--disable-gpu","--disable-software-rasterizer"]}browser=await chromium.launch({executablePath,args,headless:true});const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:3000';
for(let i=0;i<70;i++){try{if((await fetch(base)).ok)break}catch{}await new Promise(r=>setTimeout(r,500))}await page.goto(base);assert.equal(await page.locator('article[data-sku]').count(),86);assert.equal(await page.getByRole('button',{name:'Comprar',exact:true}).count(),86);const categories=await page.locator('#categorias a').all();assert.equal(categories.length,9);
for(const link of categories){const href=await link.getAttribute('href'),popupPromise=page.waitForEvent('popup');await link.click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');assert.ok(popup.url().endsWith(href));assert.ok(await popup.locator('article[data-sku]').count()>0);await popup.close()}
await page.locator('article[data-sku="00001"]').getByRole('button',{name:'Comprar',exact:true}).click();await page.getByRole('link',{name:'Meu pedido',exact:true}).click();await page.waitForURL('**/carrinho');await page.getByLabel('Quantidade').fill('2');await page.reload();await page.getByLabel('Quantidade').waitFor();assert.equal(await page.getByLabel('Quantidade').inputValue(),'2');await page.getByRole('link',{name:'Finalizar compra',exact:true}).click();await page.waitForURL('**/checkout');
const email=`test-${randomUUID()}@example.com`;const fields={name:'Cliente Navegador',phone:'11900000000',whatsapp:'11900000000',email,cep:'01001000',street:'Rua Teste',number:'1',district:'Centro',city:'São Paulo',state:'SP'};for(const [key,value]of Object.entries(fields))await page.locator(`input[name="${key}"]`).fill(value);await page.getByRole('button',{name:'Finalizar compra',exact:true}).click();await page.getByRole('heading',{name:'Pedido criado!'}).waitFor();const href=await page.getByRole('link',{name:'Enviar pedido pelo WhatsApp'}).getAttribute('href');assert.ok(href.startsWith('https://wa.me/5511940216955?'));order=await db.order.findFirst({where:{customer:{email}}});customerId=order.customerId;assert.equal(order.quote,true);await page.getByRole('link',{name:'Acompanhar pedido e pagamento'}).click();await page.waitForURL('**/pedidos/**');await page.getByRole('heading',{name:order.number}).waitFor();assert.ok((await page.locator('main').innerText()).includes('Nenhuma cobrança foi feita.'));
await page.getByRole('link',{name:'Meu pedido',exact:true}).click();await page.getByText('Seu pedido está vazio.').waitFor();await page.goto(base+'/admin');await page.waitForURL('**/admin-login');const password=require('fs').readFileSync('.env','utf8').match(/ADMIN_PASSWORD="(.*?)"/)[1];await page.locator('input[name="password"]').fill(password);await page.getByRole('button',{name:'Entrar',exact:true}).click();await page.getByRole('heading',{name:'Dashboard Gold Fish'}).waitFor();await page.getByText(order.number).waitFor();
await page.setViewportSize({width:390,height:844});for(const route of ['/','/categorias/boias','/categorias/bolsas-para-pesca','/carrinho','/checkout']){await page.goto(base+route);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' overflow')}
await page.goto(base+'/categorias/boias');await page.screenshot({path:'/tmp/gf-merged-mobile.png',fullPage:false});await page.setViewportSize({width:1440,height:1750});await page.goto(base);await page.screenshot({path:'/workspace/scratch/eca791411e5b/gold-fish-previa.png',fullPage:false});assert.deepEqual(errors,[]);console.log('PASS UI: 86 botões Comprar; 9 categorias em novas abas; quantidade/reload; finalizar compra; pedido/mensagem/WhatsApp; acompanhamento; carrinho vazio; admin; mobile sem overflow; zero erros JS.');
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();if(order)await db.order.delete({where:{id:order.id}});if(customerId)await db.customer.delete({where:{id:customerId}});await db.$disconnect()});
