import Link from "next/link";
export const metadata={title:"Sobre nós | GOLD FISH",description:"Conheça a GOLD FISH e nossa seleção de produtos e acessórios para pesca."};
export default function About(){
 return <main className="container py-12 md:py-20">
  <div className="max-w-3xl"><p className="text-sky-700 font-bold tracking-widest text-sm">CONHEÇA A GOLD FISH</p><h1 className="text-4xl md:text-5xl font-black mt-3">Sobre nós</h1><p className="text-xl text-slate-600 mt-6 leading-relaxed">A pesca começa muito antes do primeiro lançamento: começa na escolha dos equipamentos que vão acompanhar você.</p></div>
  <section className="card p-7 md:p-12 mt-10 grid md:grid-cols-[1fr_220px] gap-8 items-center"><div><h2 className="text-2xl font-black">Produtos para cada pescaria</h2><p className="text-slate-600 leading-relaxed mt-4">A GOLD FISH reúne produtos e acessórios de pesca em um catálogo organizado para facilitar a sua escolha. Aqui você encontra boias, linhas, iscas, bolsas e outros itens para preparar seu equipamento.</p><p className="text-slate-600 leading-relaxed mt-4">Nosso objetivo é tornar a montagem do seu pedido simples: explore as categorias, adicione os produtos ao carrinho e conte com o atendimento da loja para confirmar preços, disponibilidade e os detalhes da compra.</p></div><img src="/gold-fish-logo.jpeg" alt="GOLD FISH Pesca" className="w-full max-w-56 mx-auto object-contain"/></section>
  <section className="grid md:grid-cols-3 gap-5 mt-8" aria-label="Como comprar na GOLD FISH"><div className="card p-7"><h2 className="font-bold text-lg">Explore o catálogo</h2><p className="text-slate-600 mt-3 leading-relaxed">Navegue pelas categorias e consulte os produtos para montar o equipamento da sua próxima pescaria.</p></div><div className="card p-7"><h2 className="font-bold text-lg">Monte seu carrinho</h2><p className="text-slate-600 mt-3 leading-relaxed">Visualize os itens escolhidos, ajuste as quantidades e revise seu pedido antes de finalizar.</p></div><div className="card p-7"><h2 className="font-bold text-lg">Converse com a equipe</h2><p className="text-slate-600 mt-3 leading-relaxed">Depois de criar o pedido, use o botão de WhatsApp para enviar os detalhes e combinar a compra com a loja.</p></div></section>
  <div className="mt-10 flex flex-wrap gap-4"><Link href="/#produtos" className="btn">Explorar produtos</Link><Link href="/carrinho" className="btn">Acessar carrinho</Link></div>
 </main>
}
