export const dynamic = "force-dynamic";
import { db } from "@/lib/db"; import Link from "next/link"; import { ProductCard } from "@/components/ProductCard"; import {CatalogNotice} from "@/components/CatalogNotice";
export default async function Home(){
 const products=await db.product.findMany({where:{status:"ACTIVE"},include:{category:true},orderBy:{sku:"asc"}}); const cats=await db.category.findMany({where:{products:{some:{status:"ACTIVE"}}},orderBy:{name:"asc"},include:{_count:{select:{products:{where:{status:"ACTIVE"}}}}}});
 return <main>
  <section className="bg-gradient-to-br from-[#071b2b] via-[#0b3a5b] to-[#0d5662] text-white"><div className="container py-20 md:py-28 grid md:grid-cols-2 gap-10 items-center"><div><span className="text-sm font-bold tracking-widest text-sky-200">GOLD FISH • PESCA</span><h1 className="text-4xl md:text-6xl font-black mt-4 leading-tight">Equipamentos certos para quem leva a pesca a sério.</h1><p className="text-slate-200 text-lg mt-5 max-w-xl">Encontre produtos selecionados para tornar cada pescaria uma experiência melhor.</p><a className="btn mt-7" style={{background:"white",color:"#0b3a5b"}} href="#produtos">COMPRAR AGORA</a></div><div className="card p-6 bg-white/10 border-white/20"><img src="/gold-fish-logo.jpeg" alt="Gold Fish Pesca" className="w-full rounded-xl bg-white"/></div></div></section>
  <section id="categorias" className="container py-12"><h2 className="text-3xl font-black">Categorias</h2><div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-6">{cats.map(c=><Link href={`/categorias/${c.slug}`} key={c.id} target="_blank" rel="noopener noreferrer" className="card p-5 font-bold hover:border-sky-700" aria-label={`${c.name} — abre em nova aba`}>{c.name}<span className="block text-xs font-normal text-slate-500 mt-2">{c._count.products} produtos · abrir em nova aba ↗</span></Link>)}</div></section>
  <section id="produtos" className="container py-10"><CatalogNotice/><div className="flex justify-between items-end"><div><p className="text-sky-700 font-bold">SELEÇÃO GOLD FISH</p><h2 className="text-3xl font-black">Catálogo de produtos</h2></div></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5 mt-7">{products.map(p=><ProductCard product={p} category={p.category.name} key={p.id}/>)}</div></section>
  <section id="sobre" className="container py-12 scroll-mt-24"><div className="card p-8 md:p-12"><p className="text-sky-700 font-bold">CONHEÇA A GOLD FISH</p><h2 className="text-3xl font-black mt-2">Sua próxima pescaria começa aqui</h2><p className="text-slate-600 mt-4 max-w-3xl leading-relaxed">Reunimos produtos e acessórios de pesca em um catálogo organizado para facilitar sua escolha. Explore nossas categorias, monte seu carrinho e conte com a equipe da loja para confirmar os detalhes do pedido.</p><Link href="/sobre" className="btn mt-6">Saiba mais sobre nós</Link></div></section>
 </main>
}
